//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Коррекция.
    /// </summary>
    // *** Start programmer edit section *** (Коррекция CustomAttributes)

    // *** End programmer edit section *** (Коррекция CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КоррекцияE", new string[] {
            "Кадрирование as \'Кадрирование\'",
            "ЧБЦвет as \'Ч б цвет\'"})]
    public class Коррекция : ICSSoft.STORMNET.DataObject
    {
        
        private bool fКадрирование;
        
        private bool fЧБЦвет;
        
        private IIS.KursovayaRabota.ПечатьФото fПечатьФото;
        
        // *** Start programmer edit section *** (Коррекция CustomMembers)

        // *** End programmer edit section *** (Коррекция CustomMembers)

        
        /// <summary>
        /// Кадрирование.
        /// </summary>
        // *** Start programmer edit section *** (Коррекция.Кадрирование CustomAttributes)

        // *** End programmer edit section *** (Коррекция.Кадрирование CustomAttributes)
        public virtual bool Кадрирование
        {
            get
            {
                // *** Start programmer edit section *** (Коррекция.Кадрирование Get start)

                // *** End programmer edit section *** (Коррекция.Кадрирование Get start)
                bool result = this.fКадрирование;
                // *** Start programmer edit section *** (Коррекция.Кадрирование Get end)

                // *** End programmer edit section *** (Коррекция.Кадрирование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Коррекция.Кадрирование Set start)

                // *** End programmer edit section *** (Коррекция.Кадрирование Set start)
                this.fКадрирование = value;
                // *** Start programmer edit section *** (Коррекция.Кадрирование Set end)

                // *** End programmer edit section *** (Коррекция.Кадрирование Set end)
            }
        }
        
        /// <summary>
        /// ЧБЦвет.
        /// </summary>
        // *** Start programmer edit section *** (Коррекция.ЧБЦвет CustomAttributes)

        // *** End programmer edit section *** (Коррекция.ЧБЦвет CustomAttributes)
        public virtual bool ЧБЦвет
        {
            get
            {
                // *** Start programmer edit section *** (Коррекция.ЧБЦвет Get start)

                // *** End programmer edit section *** (Коррекция.ЧБЦвет Get start)
                bool result = this.fЧБЦвет;
                // *** Start programmer edit section *** (Коррекция.ЧБЦвет Get end)

                // *** End programmer edit section *** (Коррекция.ЧБЦвет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Коррекция.ЧБЦвет Set start)

                // *** End programmer edit section *** (Коррекция.ЧБЦвет Set start)
                this.fЧБЦвет = value;
                // *** Start programmer edit section *** (Коррекция.ЧБЦвет Set end)

                // *** End programmer edit section *** (Коррекция.ЧБЦвет Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.KursovayaRabota.ПечатьФото.
        /// </summary>
        // *** Start programmer edit section *** (Коррекция.ПечатьФото CustomAttributes)

        // *** End programmer edit section *** (Коррекция.ПечатьФото CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПечатьФото"})]
        public virtual IIS.KursovayaRabota.ПечатьФото ПечатьФото
        {
            get
            {
                // *** Start programmer edit section *** (Коррекция.ПечатьФото Get start)

                // *** End programmer edit section *** (Коррекция.ПечатьФото Get start)
                IIS.KursovayaRabota.ПечатьФото result = this.fПечатьФото;
                // *** Start programmer edit section *** (Коррекция.ПечатьФото Get end)

                // *** End programmer edit section *** (Коррекция.ПечатьФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Коррекция.ПечатьФото Set start)

                // *** End programmer edit section *** (Коррекция.ПечатьФото Set start)
                this.fПечатьФото = value;
                // *** Start programmer edit section *** (Коррекция.ПечатьФото Set end)

                // *** End programmer edit section *** (Коррекция.ПечатьФото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КоррекцияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КоррекцияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КоррекцияE", typeof(IIS.KursovayaRabota.Коррекция));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Коррекция.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfКоррекция CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfКоррекция CustomAttributes)
    public class DetailArrayOfКоррекция : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.KursovayaRabota.DetailArrayOfКоррекция members)

        // *** End programmer edit section *** (IIS.KursovayaRabota.DetailArrayOfКоррекция members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Коррекция by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Коррекция.
        /// </summary>
        public DetailArrayOfКоррекция(IIS.KursovayaRabota.ПечатьФото fПечатьФото) : 
                base(typeof(Коррекция), ((ICSSoft.STORMNET.DataObject)(fПечатьФото)))
        {
        }
        
        public IIS.KursovayaRabota.Коррекция this[int index]
        {
            get
            {
                return ((IIS.KursovayaRabota.Коррекция)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.KursovayaRabota.Коррекция dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
