//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оплата.
    /// </summary>
    // *** Start programmer edit section *** (Оплата CustomAttributes)

    // *** End programmer edit section *** (Оплата CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОплатаE", new string[] {
            "ДатаОплаты as \'Дата оплаты\'",
            "ВремяОплаты as \'Время оплаты\'",
            "ВидОплаты as \'Вид оплаты\'",
            "ПечатьФото as \'Печать фото\'",
            "ПечатьФото.НомерЗаказа as \'Номер заказа\'"}, Hidden=new string[] {
            "ПечатьФото.НомерЗаказа"})]
    [MasterViewDefineAttribute("ОплатаE", "ПечатьФото", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерЗаказа")]
    [View("ОплатаL", new string[] {
            "ДатаОплаты as \'Дата оплаты\'",
            "ВремяОплаты as \'Время оплаты\'",
            "ВидОплаты as \'Вид оплаты\'",
            "ПечатьФото.НомерЗаказа as \'Номер заказа\'"})]
    public class Оплата : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОплаты;
        
        private string fВремяОплаты;
        
        private IIS.KursovayaRabota.ТипОплаты fВидОплаты;
        
        private IIS.KursovayaRabota.ПечатьФото fПечатьФото;
        
        // *** Start programmer edit section *** (Оплата CustomMembers)

        // *** End programmer edit section *** (Оплата CustomMembers)

        
        /// <summary>
        /// ВидОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.ВидОплаты CustomAttributes)

        // *** End programmer edit section *** (Оплата.ВидОплаты CustomAttributes)
        public virtual IIS.KursovayaRabota.ТипОплаты ВидОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.ВидОплаты Get start)

                // *** End programmer edit section *** (Оплата.ВидОплаты Get start)
                IIS.KursovayaRabota.ТипОплаты result = this.fВидОплаты;
                // *** Start programmer edit section *** (Оплата.ВидОплаты Get end)

                // *** End programmer edit section *** (Оплата.ВидОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.ВидОплаты Set start)

                // *** End programmer edit section *** (Оплата.ВидОплаты Set start)
                this.fВидОплаты = value;
                // *** Start programmer edit section *** (Оплата.ВидОплаты Set end)

                // *** End programmer edit section *** (Оплата.ВидОплаты Set end)
            }
        }
        
        /// <summary>
        /// ВремяОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.ВремяОплаты CustomAttributes)

        // *** End programmer edit section *** (Оплата.ВремяОплаты CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.ВремяОплаты Get start)

                // *** End programmer edit section *** (Оплата.ВремяОплаты Get start)
                string result = this.fВремяОплаты;
                // *** Start programmer edit section *** (Оплата.ВремяОплаты Get end)

                // *** End programmer edit section *** (Оплата.ВремяОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.ВремяОплаты Set start)

                // *** End programmer edit section *** (Оплата.ВремяОплаты Set start)
                this.fВремяОплаты = value;
                // *** Start programmer edit section *** (Оплата.ВремяОплаты Set end)

                // *** End programmer edit section *** (Оплата.ВремяОплаты Set end)
            }
        }
        
        /// <summary>
        /// ДатаОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.ДатаОплаты CustomAttributes)

        // *** End programmer edit section *** (Оплата.ДатаОплаты CustomAttributes)
        public virtual System.DateTime ДатаОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.ДатаОплаты Get start)

                // *** End programmer edit section *** (Оплата.ДатаОплаты Get start)
                System.DateTime result = this.fДатаОплаты;
                // *** Start programmer edit section *** (Оплата.ДатаОплаты Get end)

                // *** End programmer edit section *** (Оплата.ДатаОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.ДатаОплаты Set start)

                // *** End programmer edit section *** (Оплата.ДатаОплаты Set start)
                this.fДатаОплаты = value;
                // *** Start programmer edit section *** (Оплата.ДатаОплаты Set end)

                // *** End programmer edit section *** (Оплата.ДатаОплаты Set end)
            }
        }
        
        /// <summary>
        /// Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.ПечатьФото CustomAttributes)

        // *** End programmer edit section *** (Оплата.ПечатьФото CustomAttributes)
        [PropertyStorage(new string[] {
                "ПечатьФото"})]
        [NotNull()]
        public virtual IIS.KursovayaRabota.ПечатьФото ПечатьФото
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.ПечатьФото Get start)

                // *** End programmer edit section *** (Оплата.ПечатьФото Get start)
                IIS.KursovayaRabota.ПечатьФото result = this.fПечатьФото;
                // *** Start programmer edit section *** (Оплата.ПечатьФото Get end)

                // *** End programmer edit section *** (Оплата.ПечатьФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.ПечатьФото Set start)

                // *** End programmer edit section *** (Оплата.ПечатьФото Set start)
                this.fПечатьФото = value;
                // *** Start programmer edit section *** (Оплата.ПечатьФото Set end)

                // *** End programmer edit section *** (Оплата.ПечатьФото Set end)
            }
        }
        
        // *** Start programmer edit section *** (Оплата.Печать CustomAttributes)

        // *** End programmer edit section *** (Оплата.Печать CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Печать()
        {
            // *** Start programmer edit section *** (Оплата.Печать method implementation)

            return;
            // *** End programmer edit section *** (Оплата.Печать method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОплатаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаE", typeof(IIS.KursovayaRabota.Оплата));
                }
            }
            
            /// <summary>
            /// "ОплатаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаL", typeof(IIS.KursovayaRabota.Оплата));
                }
            }
        }
    }
}
