//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип оплаты.
    /// </summary>
    // *** Start programmer edit section *** (ТипОплаты CustomAttributes)

    // *** End programmer edit section *** (ТипОплаты CustomAttributes)
    public enum ТипОплаты
    {
        
        // *** Start programmer edit section *** (ТипОплаты.Наличные CustomAttributes)

        // *** End programmer edit section *** (ТипОплаты.Наличные CustomAttributes)
        [Caption("Наличные")]
        Наличные,
        
        // *** Start programmer edit section *** (ТипОплаты.QrКод CustomAttributes)

        // *** End programmer edit section *** (ТипОплаты.QrКод CustomAttributes)
        [Caption("Qr код")]
        QrКод,
    }
}
